### ISSUE TITLE
NPC:Highlord Tirion Fordring

### ISSUE THREAD

**Issue by Warglaive** [Warglaive/DragonFireOriginal-3.3.5#342]
http://www.wowhead.com/npc=28179/highlord-tirion-fordring
Проблема при това NPC е, че е невидимо за играчите, phasemask 1, но въпреки това се скрива.
NPC-то е за този quest:
http://www.wowhead.com/quest=13226/judgment-day-comes

**Comment by FALL1N1** [comment]
If you have already quested at the AC camp, then this quest is not available.

and can confirm this if you do any quests at crusaders pinnacle phasing changes, think bug here is that you can still take this quest after doing quests there when you should not be able to, and that's why cant be turned in,

If you do this quest on a char which has never done any crusaders pinnacle quest then this works fine, this is breadcrumb quest which is meant to lead there,
